---
  api_url:
    description: "Salt NetAPI URL if using remote server."
    type: "string"
    secret: false
    required: false
  username:
    description: "Username for Salt NetAPI integration."
    type: "string"
    secret: false
    required: false
  password:
    description: "Password for Salt NetAPI integration."
    type: "string"
    secret: true
    required: false
  eauth:
    description: "Salt external authentication system."
    type: "string"
    secret: false
    required: false
    default: pam
  verify_ssl:
    description: "True: verify the Salt API certificate is valid."
    type: "boolean"
    secret: false
    required: false
    default: true
