---
name: 'local'
runner_type: 'run-python'
description: 'Run Salt Exection Modules through Salt API'
enabled: true
entry_point: 'local.py'
parameters:
    cmd:
        description: 'The module to call'
        type: 'string'
        required: true

    args:
        description: 'Positional aruments for module'
        type: 'string'
        required: false

    kwargs:
        description: 'Key Pair arguments to pass to the module'
        type: object
        required: false
